# Generated by Django 2.2 on 2020-04-14 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=250)),
                ('namberofCases', models.IntegerField()),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.CharField(max_length=250)),
                ('date', models.DateTimeField()),
                ('city', models.ManyToManyField(related_name='city_or_district', to='bangla.City')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='city',
            name='divi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='d', to='bangla.Division'),
        ),
    ]
