# Generated by Django 2.2 on 2020-04-14 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bangla', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
