# Generated by Django 2.2 on 2020-04-15 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bangla', '0002_auto_20200414_2255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['-namberofCases']},
        ),
        migrations.AlterField(
            model_name='division',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
