# Generated by Django 2.2 on 2020-04-14 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=250, null=True)),
                ('total_cases', models.CharField(max_length=250, null=True)),
                ('total_death', models.CharField(max_length=250, null=True)),
                ('total_recover', models.CharField(max_length=250, null=True)),
                ('active_cases', models.CharField(max_length=250, null=True)),
                ('total_case_per_minion_pop', models.CharField(max_length=250, null=True)),
                ('total_death_per_minion_pop', models.CharField(max_length=250, null=True)),
                ('create', models.DateTimeField(auto_now=True, db_index=True)),
                ('new_case', models.IntegerField(blank=True, default=0)),
                ('new_death', models.IntegerField(blank=True, default=0)),
            ],
            options={
                'ordering': ['-new_case', '-new_death', '-create'],
            },
        ),
        migrations.CreateModel(
            name='NewCases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_cases', models.IntegerField()),
                ('new_death', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True, db_index=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Country')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.AddField(
            model_name='country',
            name='new_cases',
            field=models.ManyToManyField(related_name='newcases', to='main.NewCases'),
        ),
    ]
